version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - PGPASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    server: 
        restart: always
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        stdin_open: true
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
